/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template

 */

package form;
import config.Koneksi;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ivanda
 */
public class FormPemesanan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPemesanan.class.getName());

    /**
     * Creates new form FormPemesanan
     */
    public FormPemesanan() {
    initComponents();

    txtIdPemesanan.setEditable(false);
    txtHarga.setEditable(false);
    txtTotal.setEditable(false);
    txtTanggal.setEditable(false);

    autoID();
    tanggalHariIni();
    tampilUser();
    tampilProduk();
    tampilData();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void autoID() {

}
   private void tanggalHariIni() {

    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    Date tanggal = new Date();

    txtTanggal.setText(format.format(tanggal));

}
    
    private void tampilData() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("User");
    model.addColumn("Produk");
    model.addColumn("Jumlah");
    model.addColumn("Total");
    model.addColumn("Tanggal");

    try {

        Connection con = Koneksi.getConnection();

        Statement st = con.createStatement();

        String sql = "SELECT p.id_pemesanan, u.username, pr.nama_produk, "
                + "p.jumlah, p.total, p.tanggal "
                + "FROM pemesanan p "
                + "JOIN users u ON p.id_user=u.id_user "
                + "JOIN produk pr ON p.id_produk=pr.id_produk";

        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id_pemesanan"),
                rs.getString("username"),
                rs.getString("nama_produk"),
                rs.getInt("jumlah"),
                rs.getInt("total"),
                rs.getDate("tanggal")
            });

        }

        tblPemesanan.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}

private void tampilUser() {

    try {

        Connection con = Koneksi.getConnection();

        Statement st = con.createStatement();

        ResultSet rs = st.executeQuery("SELECT * FROM users");

        cbUser.removeAllItems();

        while (rs.next()) {

            cbUser.addItem(rs.getString("username"));

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}

private void tampilProduk() {

    try {

        Connection con = Koneksi.getConnection();

        Statement st = con.createStatement();

        ResultSet rs = st.executeQuery("SELECT * FROM produk");

        cbProduk.removeAllItems();

        while (rs.next()) {

            cbProduk.addItem(rs.getString("nama_produk"));

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}

private void hitungTotal() {

    try {

        int harga = Integer.parseInt(txtHarga.getText());
        int jumlah = Integer.parseInt(txtJumlah.getText());

        int total = harga * jumlah;

        txtTotal.setText(String.valueOf(total));

    } catch (Exception e) {

        txtTotal.setText("");

    }

}

private void bersihkanForm() {

    txtIdPemesanan.setText("");
    cbUser.setSelectedIndex(0);
    cbProduk.setSelectedIndex(0);
    txtHarga.setText("");
    txtJumlah.setText("");
    txtTotal.setText("");

    tanggalHariIni();

    cbUser.requestFocus();

}

private void simpanData() {

    try {

        Connection con = Koneksi.getConnection();

        // Ambil id_produk berdasarkan nama produk
        Statement st = con.createStatement();

        ResultSet rs = st.executeQuery(
                "SELECT id_produk FROM produk WHERE nama_produk='" + cbProduk.getSelectedItem() + "'");

        int idProduk = 0;

        if (rs.next()) {
            idProduk = rs.getInt("id_produk");
        }

        // Karena login masih admin, id_user = 1
        int idUser = 1;

        ResultSet rsStok = st.executeQuery(
        "SELECT stok FROM produk WHERE id_produk=" + idProduk);

if (rsStok.next()) {

    int stok = rsStok.getInt("stok");
    int jumlah = Integer.parseInt(txtJumlah.getText());

    if (stok == 0) {

        JOptionPane.showMessageDialog(this,
                "Stok produk habis!");

        return;

    }

    if (jumlah > stok) {

        JOptionPane.showMessageDialog(this,
                "Jumlah melebihi stok yang tersedia!");

        return;

    }

}
        
        String sql = "INSERT INTO pemesanan(id_user,id_produk,jumlah,total,tanggal) VALUES(?,?,?,?,?)";

        java.sql.PreparedStatement ps = con.prepareStatement(sql);

        ps.setInt(1, idUser);
        ps.setInt(2, idProduk);
        ps.setInt(3, Integer.parseInt(txtJumlah.getText()));
        ps.setInt(4, Integer.parseInt(txtTotal.getText()));
        ps.setString(5, txtTanggal.getText());

        ps.executeUpdate();

// Kurangi stok produk
String sqlStok = "UPDATE produk SET stok = stok - ? WHERE id_produk = ?";

PreparedStatement psStok = con.prepareStatement(sqlStok);

psStok.setInt(1, Integer.parseInt(txtJumlah.getText()));
psStok.setInt(2, idProduk);

psStok.executeUpdate();
tampilData();
bersihkanForm();
tampilProduk();

JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");

tampilData();
bersihkanForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}

private void ubahData() {

    try {

        Connection con = Koneksi.getConnection();

        // Ambil id_produk
        Statement st = con.createStatement();

        ResultSet rs = st.executeQuery(
                "SELECT id_produk FROM produk WHERE nama_produk='" + cbProduk.getSelectedItem() + "'");

        int idProduk = 0;

        if (rs.next()) {
            idProduk = rs.getInt("id_produk");
        }

        // sementara user masih admin
        int idUser = 1;
        ResultSet rsStok = st.executeQuery(
        "SELECT stok FROM produk WHERE id_produk=" + idProduk);

if (rsStok.next()) {

    int stok = rsStok.getInt("stok");
    int jumlah = Integer.parseInt(txtJumlah.getText());

    if (jumlah > stok) {

        JOptionPane.showMessageDialog(this,
                "Stok tidak mencukupi!");

        return;

    }

}
        String sql = "UPDATE pemesanan SET "
                + "id_user=?,"
                + "id_produk=?,"
                + "jumlah=?,"
                + "total=?,"
                + "tanggal=? "
                + "WHERE id_pemesanan=?";

        PreparedStatement ps = con.prepareStatement(sql);

        ps.setInt(1, idUser);
        ps.setInt(2, idProduk);
        ps.setInt(3, Integer.parseInt(txtJumlah.getText()));
        ps.setInt(4, Integer.parseInt(txtTotal.getText()));
        ps.setString(5, txtTanggal.getText());
        ps.setInt(6, Integer.parseInt(txtIdPemesanan.getText()));

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data berhasil diubah.");

        tampilData();
        bersihkanForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}

private void hapusData() {

    if (txtIdPemesanan.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus terlebih dahulu!");
        return;
    }

    int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus data ini?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {

        try {

            Connection con = Koneksi.getConnection();

            String sql = "DELETE FROM pemesanan WHERE id_pemesanan=?";

            PreparedStatement ps = con.prepareStatement(sql);

            ps.setInt(1, Integer.parseInt(txtIdPemesanan.getText()));

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");

            tampilData();
            bersihkanForm();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());

        }

    }

}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdPemesanan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbUser = new javax.swing.JComboBox<>();
        cbProduk = new javax.swing.JComboBox<>();
        txtHarga = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JToggleButton();
        btnUbah = new javax.swing.JToggleButton();
        btnHapus = new javax.swing.JToggleButton();
        btnBersih = new javax.swing.JToggleButton();
        spPemesanan = new javax.swing.JScrollPane();
        tblPemesanan = new javax.swing.JTable();
        btnKembali = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIdPemesanan.addActionListener(this::txtIdPemesananActionPerformed);

        jLabel1.setText("ID Pemesanan");

        cbUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbProduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProduk.addActionListener(this::cbProdukActionPerformed);

        txtJumlah.addActionListener(this::txtJumlahActionPerformed);
        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahKeyReleased(evt);
            }
        });

        jLabel2.setText("User");

        jLabel3.setText("Produk");

        jLabel4.setText("Harga");

        jLabel5.setText("Jumlah");

        jLabel6.setText("Total");

        jLabel7.setText("Tanggal");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::actionPerformed);

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnBersih.setText("Bersihkan");
        btnBersih.addActionListener(this::btnBersihActionPerformed);

        tblPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FormPemesanan.this.mouseClicked(evt);
            }
        });
        spPemesanan.setViewportView(tblPemesanan);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBersih)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(spPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBersih)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKembali)))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
      simpanData();        // TODO add your handling code here:
    }//GEN-LAST:event_actionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
    ubahData();    // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    hapusData();        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
    bersihkanForm();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBersihActionPerformed

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
      int baris = tblPemesanan.getSelectedRow();

    txtIdPemesanan.setText(tblPemesanan.getValueAt(baris, 0).toString());
    cbUser.setSelectedItem(tblPemesanan.getValueAt(baris, 1).toString());
    cbProduk.setSelectedItem(tblPemesanan.getValueAt(baris, 2).toString());
    txtJumlah.setText(tblPemesanan.getValueAt(baris, 3).toString());
    txtTotal.setText(tblPemesanan.getValueAt(baris, 4).toString());
    txtTanggal.setText(tblPemesanan.getValueAt(baris, 5).toString());  // TODO add your handling code here:
    }//GEN-LAST:event_mouseClicked

    private void cbProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProdukActionPerformed
    try {

        Connection con = Koneksi.getConnection();

        Statement st = con.createStatement();

        String sql = "SELECT harga, stok FROM produk WHERE nama_produk='" + cbProduk.getSelectedItem() + "'";

        ResultSet rs = st.executeQuery(sql);

        if (rs.next()) {

            txtHarga.setText(rs.getString("harga"));
            
                }
  } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProdukActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyReleased
    hitungTotal();        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahKeyReleased

    private void txtIdPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPemesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPemesananActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
    new FormMenu().setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPemesanan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBersih;
    private javax.swing.JToggleButton btnHapus;
    private javax.swing.JToggleButton btnKembali;
    private javax.swing.JToggleButton btnSimpan;
    private javax.swing.JToggleButton btnUbah;
    private javax.swing.JComboBox<String> cbProduk;
    private javax.swing.JComboBox<String> cbUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane spPemesanan;
    private javax.swing.JTable tblPemesanan;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdPemesanan;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
